name: test_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.0.0
  path_provider: ^2.0.11
  flutter_tts: ^3.2.0
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.4
  shared_preferences: ^2.0.8
  image_picker: ^0.8.4+4
  multi_select_flutter: ^4.1.1
  provider: ^5.0.0
  flutter_local_notifications: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image.png
    - assets/image2.png
    - assets/